<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Hermod\Hermod\Hermod.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\ChargingStationManufacturer\AdminStatus\" />
    <Folder Include="Entities\ChargingStationManufacturer\ChargingStation\EVSE\Group\AdminStatus\" />
    <Folder Include="Entities\ChargingStationManufacturer\ChargingStation\Group\AdminStatus\" />
    <Folder Include="Entities\ChargingStationOperator\ChargingPool\Group\AdminStatus\" />
    <Folder Include="Entities\ChargingStationOperator\Group\" />
    <Folder Include="Entities\EMobilityProvider\Group\" />
  </ItemGroup>

</Project>
